input: "/path/to/data.czi"
output: "/path/to/output/"
#skew_direction: Y
#deskew_angle:
processing: crop
deconvolution: cuda_gpu
deconvolution_num_iter: 20
deconvolution_psf:
 - "/path/to/psf/c1.tif"
 - "/path/to/psf/c2.tif"
 - "/path/to/psf/c3.tif"
 - "/path/to/psf/c4.tif"
roi_file: "/path/to/roi_file.zip"
voxel_sizes:
  - 0.3      #dz
  - 0.123    #dy
  - 0.456    #dx
#file_extension:
time_range:
  - 1
  - 5
channel_range:
  - 0
  - 2
#workflow_path:
output_file_type: tif
#channel:



