site_name: napari_lattice

markdown_extensions:
- mkdocs-click
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences 
- admonition
- pymdownx.details
- attr_list
- md_in_html
- pymdownx.blocks.caption
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- index.md
- installation.md
- "Napari Plugin":
  - "Napari Plugin": napari_plugin/index.md
  - "Initializing the Plugin": napari_plugin/starting_plugin.md
  - "Using the Plugin": napari_plugin/plugin_usage.md
- cli.md
- api.md
- workflow.md
- development.md
- "Supporting Resources":
  - "Supporting Resources": miscellaneous/index.md
  - "Defining ROIs for cropping": miscellaneous/rois_cropping.md
plugins:
- search
- mkdocs-video:
    is_video: True
    video_muted: True
    video_controls: True
    css_style:
      width: "75%"
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          heading_level: 3
          show_root_heading: true
          # Inheritance and source are useful for advanced users,
          # but possibly confusing for others
          show_bases: false
          show_source: false
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
          extensions:
          - griffe_fieldz:
              include_inherited: true

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tabs #tabs on top
    - navigation.tabs.sticky #visible even when scrolling down
    - navigation.sections
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

# Google analytics
extra:
  analytics:
    provider: google
    property: G-S3Y319X195

