site_name: napari_lattice

markdown_extensions:
- mkdocs-click
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences 
- admonition
- pymdownx.details
- attr_list
- md_in_html
- pymdownx.blocks.caption

nav:
- index.md
- installation.md
- napari_plugin.md
- cli.md
- api.md
- workflow.md
- development.md

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          heading_level: 3
          show_root_heading: true
          # Inheritance and source are useful for advanced users,
          # but possibly confusing for others
          show_bases: false
          show_source: false
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
          extensions:
          - griffe_fieldz:
              include_inherited: true

theme:
  name: material
  features:
    - content.code.copy
