name: 'Lint'
inputs:
  directory:
    description: 'Path to the package to lint'
    required: true
  python:
    description: 'Path to the python interpreter to use'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        pip install fawltydeps
        fawltydeps --check --detailed --verbose
      shell: bash -l {0}
      working-directory: ${{ inputs.directory }}

    - uses: jakebailey/pyright-action@v1
      with:
        working-directory: ${{ inputs.directory }}
        python-path: ${{ inputs.python }}
