name: 'Lint'
inputs:
  directory:
    description: 'Path to the package to lint'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        pip install fawltydeps==0.12.0
        fawltydeps --check ${{ inputs.directory }}

    - uses: jakebailey/pyright-action@v1
      with:
        version: "1.6.0"
        working-directory: ${{ inputs.directory }}
